const $=s=>document.querySelector(s);const API='/api';let token=localStorage.getItem('g3d_token')||'';const toast=t=>{const e=$('#toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2500)};async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur');return d}
const content={
desinfection:{title:'Désinfection professionnelle',icon:'🧴',form:'Désinfection',intro:'Nous vous proposons des solutions de désinfection professionnelles avec des produits de qualité et une méthode adaptée à chaque environnement.',offers:['Diagnostic de la zone à traiter','Désinfection des surfaces et points de contact','Maisons, bureaux, commerces et locaux professionnels','Intervention ponctuelle ou régulière','Conseils après intervention'],method:'Nous sélectionnons la méthode et les produits en fonction du type de local, du niveau de traitement recherché et des contraintes du site. Notre équipe explique au client le déroulement de l’intervention avant le traitement.',reviews:['Équipe ponctuelle et intervention bien organisée.','Service sérieux et explications claires.','Bonne réactivité et suivi professionnel.']},
desinsectisation:{title:'Désinsectisation',icon:'🪳',form:'Désinsectisation',intro:'Traitement ciblé contre les insectes nuisibles dans les habitations et locaux professionnels.',offers:['Cafards et blattes','Moustiques','Punaises et autres insectes','Zones sensibles','Conseils de prévention'],method:'Le traitement est adapté au nuisible, au niveau d’infestation et aux caractéristiques du site.',reviews:['Intervention rapide et efficace.','Bonne organisation du traitement.','Suivi professionnel après intervention.']},
deratisation:{title:'Dératisation',icon:'🐀',form:'Dératisation',intro:'Prévention et traitement de la présence de rats et souris.',offers:['Inspection du site','Identification des passages','Plan de traitement','Prévention du retour','Suivi si nécessaire'],method:'Nous cherchons à traiter le problème et à identifier les causes favorisant la présence des rongeurs.',reviews:['Diagnostic clair.','Très bonne prise en charge.','Conseils utiles pour sécuriser les zones sensibles.']},
nettoyage:{title:'Nettoyage des locaux',icon:'🧹',form:'Nettoyage des locaux',intro:'Nettoyage adapté aux bureaux, commerces, maisons et fins de chantier.',offers:['Bureaux et commerces','Sols et surfaces','Maisons et appartements','Remise en état','Prestations régulières'],method:'Nous organisons les tâches selon la surface, la fréquentation et les priorités du client.',reviews:['Locaux propres et équipe organisée.','Très satisfait du nettoyage.','Travail soigné et bonne disponibilité.']},
espaces:{title:'Pulvérisation des espaces verts',icon:'🌿',form:'Pulvérisation espaces verts',intro:'Traitement des jardins, cours et espaces extérieurs.',offers:['Jardins','Cours','Zones autour des bâtiments','Traitement ciblé','Programme régulier'],method:'Nous évaluons la zone avant intervention afin d’adapter le traitement au site.',reviews:['Intervention bien organisée.','Équipe sérieuse.','Bonne coordination.']},
pulverisation:{title:'Pulvérisation professionnelle',icon:'💨',form:'Pulvérisation professionnelle',intro:'Solutions pour entrepôts, grandes surfaces et espaces professionnels.',offers:['Étude du site','Grandes surfaces','Entrepôts','Organisation par zones','Suivi'],method:'Nous adaptons le matériel et la méthode d’application aux contraintes du site.',reviews:['Bonne préparation.','Intervention professionnelle.','Suivi sérieux.']}
};
const sd=$('#serviceDialog'),details=$('#serviceDetails');document.querySelectorAll('.service-card').forEach(c=>c.onclick=()=>openService(c.dataset.service));function openService(k){const s=content[k];details.innerHTML=`<div class="service-hero"><div style="font-size:2.4rem">${s.icon}</div><h2>${s.title}</h2><p>${s.intro}</p></div><div class="service-body"><div class="detail-grid"><div class="detail-box"><h3>Ce que nous vous proposons</h3><ul class="checks">${s.offers.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="detail-box"><h3>Pourquoi nous choisir</h3><ul class="checks"><li>Devis clair</li><li>Intervention organisée</li><li>Suivi client</li><li>Solutions adaptées</li></ul></div></div><div class="quality"><h3>Produits de qualité & méthode professionnelle</h3><p>${s.method}</p></div><h3>Avis de clients et partenaires</h3><div class="reviews">${s.reviews.map(x=>`<div class="review"><div class="stars">★★★★★</div><b>Client / partenaire</b><p>“${x}”</p><small>Exemple de présentation</small></div>`).join('')}</div><p class="review-note">Remplacez ces exemples par de vrais avis lorsque vous en disposez.</p><div class="detail-actions"><button class="primary" onclick="book('${s.form}')">Demander une intervention</button><a class="secondary" href="tel:+224620242979">Appeler</a></div></div>`;sd.showModal()}$('#closeService').onclick=()=>sd.close();window.book=s=>{sd.close();$('#serviceSelect').value=s;$('#reservation').scrollIntoView({behavior:'smooth'})};
const auth=$('#authDialog'),client=$('#clientDialog'),admin=$('#adminDialog');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#registerBtn').onclick=()=>auth.showModal();$('#accountBtn').onclick=async()=>{if(!token)return auth.showModal();await openAccount()};document.querySelectorAll('[data-show]').forEach(b=>b.onclick=()=>{const reg=b.dataset.show==='register';$('#registerForm').hidden=!reg;$('#loginForm').hidden=reg});
$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));const r=await api('/register',{method:'POST',body:JSON.stringify(d)});token=r.token;localStorage.setItem('g3d_token',token);auth.close();toast('Compte créé');await openAccount()}catch(x){toast(x.message)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=Object.fromEntries(new FormData(e.target));const r=await api('/login',{method:'POST',body:JSON.stringify(d)});token=r.token;localStorage.setItem('g3d_token',token);auth.close();if(r.user.role==='admin')await openAdmin();else await openAccount()}catch(x){toast(x.message)}};
$('#requestForm').onsubmit=async e=>{e.preventDefault();if(!token)return auth.showModal();try{const d=Object.fromEntries(new FormData(e.target));await api('/requests',{method:'POST',body:JSON.stringify(d)});e.target.reset();toast('Demande enregistrée');await openAccount()}catch(x){toast(x.message)}};
async function openAccount(){try{const me=await api('/me');if(me.user.role==='admin')return openAdmin();const data=await api('/requests');$('#clientContent').innerHTML=`<h2>Bonjour ${me.user.name}</h2><p>${me.user.email} • ${me.user.phone}</p><h3>Mes demandes</h3>${data.requests.length?data.requests.map(r=>`<div class="request"><b>${r.service}</b><p>${r.location} • ${String(r.requested_date).slice(0,10)}</p><p>Statut : ${r.status}</p>${r.quote_amount?`<div class="price">${Number(r.quote_amount).toLocaleString('fr-FR')} GNF</div><button class="primary" onclick="pay('${r.id}','Orange Money')">Orange Money</button><button class="secondary" onclick="pay('${r.id}','MTN MoMo')">MTN MoMo</button>`:'<small>Devis en préparation</small>'}</div>`).join(''):'<p>Aucune demande.</p>'}<button class="secondary" id="logout">Se déconnecter</button>`;client.showModal();$('#logout').onclick=logout}catch{logout();auth.showModal()}}
window.pay=async(id,provider)=>{try{const r=await api(`/pay/${id}`,{method:'POST',body:JSON.stringify({provider})});toast(r.message||'Paiement lancé')}catch(x){toast(x.message)}};
async function openAdmin(){try{const me=await api('/me');if(me.user.role!=='admin')throw new Error('Accès refusé');const data=await api('/admin/requests');$('#adminContent').innerHTML=`<h2>Administration</h2>${data.requests.map(r=>`<div class="admin-item"><b>${r.service}</b><p>${r.customer_name}<br>${r.customer_phone}<br>${r.customer_email}<br>${r.location}</p><div class="admin-tools"><input type="number" id="a-${r.id}" value="${r.quote_amount||''}" placeholder="Montant GNF"><select id="s-${r.id}">${['Demande reçue','Devis en préparation','Devis prêt','Intervention planifiée','Intervention terminée'].map(s=>`<option ${s===r.status?'selected':''}>${s}</option>`).join('')}</select><button class="primary" onclick="saveQuote('${r.id}')">Enregistrer le devis</button></div></div>`).join('')}<button class="secondary" id="logoutAdmin">Se déconnecter</button>`;admin.showModal();$('#logoutAdmin').onclick=logout}catch(x){toast(x.message)}}
window.saveQuote=async id=>{try{await api(`/admin/requests/${id}`,{method:'PATCH',body:JSON.stringify({quoteAmount:$('#a-'+id).value,status:$('#s-'+id).value})});toast('Devis mis à jour');await openAdmin()}catch(x){toast(x.message)}};function logout(){token='';localStorage.removeItem('g3d_token');client.close();admin.close();toast('Déconnecté')}
